#!/usr/bin/env bash
# Sentinel — one-command first-time production setup.
#
# Generates .env with fresh secrets (unless one already exists), builds the
# compose stack's images, brings it up, and waits for the server to report
# healthy. Safe to re-run: an existing .env is never overwritten, so running
# this again just rebuilds/restarts (handy after `git pull`).
#
# Usage:
#   deploy/setup.sh --domain sentinel.example.com [--port 8080]
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: deploy/setup.sh --domain <domain> [--port <port>]

  --domain   the public domain your reverse proxy serves Sentinel on
             (e.g. sentinel.example.com). Required.
  --port     host port to bind the server to on 127.0.0.1 (default: 8080).
             Your reverse proxy forwards to this port.
EOF
}

domain=""
port="8080"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain)
            domain="${2:-}"
            [[ -n "$domain" ]] || { echo "error: --domain requires a value" >&2; usage >&2; exit 1; }
            shift 2
            ;;
        --domain=*)
            domain="${1#--domain=}"
            shift
            ;;
        --port)
            port="${2:-}"
            [[ -n "$port" ]] || { echo "error: --port requires a value" >&2; usage >&2; exit 1; }
            shift 2
            ;;
        --port=*)
            port="${1#--port=}"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [[ -z "$domain" ]]; then
    echo "error: --domain is required" >&2
    usage >&2
    exit 1
fi

# Strip a pasted scheme (http://, https://) and any trailing slash/path so
# --domain sentinel.example.com and --domain https://sentinel.example.com/
# both work — RP_ID must be the bare domain.
domain="${domain#http://}"
domain="${domain#https://}"
domain="${domain%%/*}"

if [[ -z "$domain" ]]; then
    echo "error: --domain resolved to an empty string after stripping scheme/path" >&2
    exit 1
fi

if ! [[ "$port" =~ ^[0-9]+$ ]]; then
    echo "error: --port must be numeric, got: $port" >&2
    exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

echo "==> domain: ${domain}   port: ${port}"

if [[ -f .env ]]; then
    echo "==> .env already exists — reusing it (not overwriting secrets). Re-run with a fresh checkout if you want new ones."
else
    echo "==> generating .env with fresh secrets"

    # Prefer openssl for the Postgres password; fall back to /dev/urandom on
    # minimal systems that don't have it.
    if command -v openssl >/dev/null 2>&1; then
        pg_password="$(openssl rand -hex 24)"
    else
        pg_password="$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    fi

    cat > .env <<EOF
# Generated by deploy/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file secret.
POSTGRES_USER=sentinel
POSTGRES_DB=sentinel
POSTGRES_PASSWORD=${pg_password}

RP_ID=${domain}
RP_ORIGIN=https://${domain}
SENTINEL_PUBLIC_URL=https://${domain}
SENTINEL_PORT=${port}
EOF

    # .env holds the DB password — keep it readable only by the owner.
    chmod 600 .env

    echo "==> secrets generated and written to ${repo_root}/.env (mode 600)"
fi

compose_bin=""
compose_args=()

if command -v podman-compose >/dev/null 2>&1; then
    compose_bin="podman-compose"
elif command -v podman >/dev/null 2>&1 && podman compose version >/dev/null 2>&1; then
    compose_bin="podman"
    compose_args=("compose")
elif command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    compose_bin="docker"
    compose_args=("compose")
else
    echo "error: none of podman-compose, 'podman compose', or 'docker compose' found." >&2
    echo "       install podman-compose (rootless Podman recommended for the VPS)." >&2
    exit 1
fi

echo "==> using: ${compose_bin} ${compose_args[*]}"

echo "==> building images (server + web, see Containerfile)"
"${compose_bin}" "${compose_args[@]}" -f compose.yaml build

echo "==> starting the stack"
"${compose_bin}" "${compose_args[@]}" -f compose.yaml up -d

echo "==> waiting for the server to report healthy on 127.0.0.1:${port}"

health_url="http://127.0.0.1:${port}/health"
healthy=""
for _ in $(seq 1 90); do
    if command -v curl >/dev/null 2>&1; then
        if curl -fsS "$health_url" >/dev/null 2>&1; then
            healthy="1"
            break
        fi
    elif command -v wget >/dev/null 2>&1; then
        if wget -q -O /dev/null "$health_url" >/dev/null 2>&1; then
            healthy="1"
            break
        fi
    else
        echo "error: neither curl nor wget found — cannot poll /health." >&2
        exit 1
    fi
    printf '.'
    sleep 1
done
echo

if [[ -z "$healthy" ]]; then
    echo "error: server did not become healthy within 90s." >&2
    echo "       check logs: ${compose_bin} ${compose_args[*]} -f compose.yaml logs server" >&2
    exit 1
fi

cat <<EOF

==> Sentinel is up and healthy on 127.0.0.1:${port}.

Next steps:

1. Point a reverse proxy at 127.0.0.1:${port} for https://${domain}.
   The app itself does not terminate TLS — your proxy must. It also must
   forward WebSocket upgrades (used by the agent channel and the SSH
   terminal).

   Minimal Caddy example:

     ${domain} {
         reverse_proxy 127.0.0.1:${port}
     }

   (Caddy forwards WebSocket upgrades automatically.)

   Minimal nginx example:

     server {
         listen 443 ssl;
         server_name ${domain};

         location / {
             proxy_pass http://127.0.0.1:${port};
             proxy_http_version 1.1;
             proxy_set_header Upgrade \$http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host \$host;
             proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto \$scheme;
         }
     }

2. Open https://${domain} and register the FIRST admin passkey. Registration
   auto-locks the moment that first admin account exists — nobody else can
   self-register after you.

3. In the console, click ADD DEVICE — it gives you a copy-paste installer
   one-liner to enroll each device.

See docs/DEPLOY.md for the full operator guide. Use deploy/update.sh to
update later.
EOF
