#!/usr/bin/env bash
# OpenScreenTime — first-time production setup. Run it once; after that the
# server looks after itself:
#
#   * .env with fresh secrets and ONE setting you choose: the public address
#     (OST_PUBLIC_URL — the passkey domain and cookie security follow from it),
#   * the server image (pulled; built here only if pulling isn't possible),
#   * the stack started and checked healthy, and a first database backup,
#   * systemd units: start at boot, nightly backup (7 kept), daily update
#     that rolls itself back if the new version isn't healthy.
#
# Safe to re-run: an existing .env is never overwritten.
#
# Usage:
#   deploy/setup.sh [--domain ost.example.com] [--port 8080] [--bind 127.0.0.1]
#                   [--no-auto-update]
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: deploy/setup.sh [--domain <domain>] [--port <port>] [--bind <address>] [--no-auto-update]

  --domain   the public domain your reverse proxy serves OpenScreenTime on
             (e.g. ost.example.com). Asked for when not given.
  --port     host port to publish the server on (default: 8080).
             Your reverse proxy forwards to this port.
  --bind     host address to publish that port on (default: 127.0.0.1).
             Only change this when the reverse proxy runs on a DIFFERENT
             machine — then use the LAN/VPN address it can reach, e.g.
             192.168.8.131. Never 0.0.0.0: the server trusts X-Forwarded-For,
             so a directly reachable port is a rate-limiter bypass.
  --no-auto-update
             don't install the daily update timer (you run deploy/update.sh).

Rootless Podman: run as the user that should own the stack (not with sudo).
Rootful Podman: run as root.
EOF
}

cd "$(dirname "${BASH_SOURCE[0]}")/.."
# shellcheck source=deploy/lib.sh
source deploy/lib.sh
repo_root="$(pwd)"

domain=""
port="8080"
bind=""
auto_update=1

need_value() { [[ -n "${2:-}" ]] || { usage >&2; ost_die "$1 requires a value"; }; }
while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain) need_value "$1" "${2:-}"; domain="$2"; shift 2 ;;
        --domain=*) domain="${1#--domain=}"; shift ;;
        --port) need_value "$1" "${2:-}"; port="$2"; shift 2 ;;
        --port=*) port="${1#--port=}"; shift ;;
        --bind) need_value "$1" "${2:-}"; bind="$2"; shift 2 ;;
        --bind=*) bind="${1#--bind=}"; shift ;;
        --no-auto-update) auto_update=0; shift ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; ost_die "unknown argument: $1" ;;
    esac
done

if [[ -f .env ]]; then
    ost_log ".env already exists — reusing it (secrets are never regenerated)"
    domain="$(ost_env OST_PUBLIC_URL "$(ost_env RP_ORIGIN)")"
    domain="${domain#https://}"; domain="${domain#http://}"; domain="${domain%%/*}"
    port="$(ost_env OST_PORT 8080)"
    bind="$(ost_env OST_BIND_ADDR)"
else
    if [[ -z "$domain" && -t 0 ]]; then
        read -r -p "Public domain for OpenScreenTime (e.g. ost.example.com): " domain
    fi
    # Accept a pasted URL too: RP_ID must be the bare host.
    domain="${domain#http://}"; domain="${domain#https://}"; domain="${domain%%/*}"
    [[ -n "$domain" ]] || { echo "error: --domain is required" >&2; usage >&2; exit 1; }
    [[ "$port" =~ ^[0-9]+$ ]] || ost_die "--port must be numeric, got: $port"
    # 0.0.0.0 is refused rather than warned about: the server trusts the
    # X-Forwarded-For its proxy appends, so anything that can reach the port
    # directly can also claim to be any client IP and walk past the rate limiter.
    if [[ "$bind" == "0.0.0.0" || "$bind" == "::" ]]; then
        ost_die "--bind $bind would expose the app port on every interface; the server trusts X-Forwarded-For, so use the specific address your reverse proxy reaches."
    fi

    ost_log "generating .env with fresh secrets"
    rand() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
    umask 077
    cat >.env <<EOF
# Generated by deploy/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file secret —
# the database password below exists nowhere else (backups copy it to backups/env.backup).
POSTGRES_USER=openscreentime
POSTGRES_DB=openscreentime
POSTGRES_PASSWORD=$(rand 24)

# The one setting: the public https address. The passkey domain (RP_ID), the
# origin and secure cookies are derived from it.
OST_PUBLIC_URL=https://${domain}
OST_PORT=${port}

# The one-time setup code the first parent types when registering. Without
# it, a fresh internet-facing install belongs to whoever finds it first.
OST_BOOTSTRAP_TOKEN=$(rand 12)
EOF
    # Only written when asked for: compose.yaml owns the loopback default.
    if [[ -n "$bind" ]]; then
        echo "OST_BIND_ADDR=${bind}" >>.env
    fi
    chmod 600 .env
    umask 022
    ost_log "secrets written to ${repo_root}/.env (mode 600)"
fi

ost_detect_engine
ost_log "using ${ENGINE} with ${COMPOSE[*]}"

health_host="${bind:-127.0.0.1}"
if [[ -n "$(ost_running_image_id)" ]]; then
    # Already set up: a re-run must not swap the image without a backup and
    # a way back, so it goes through the update path.
    ost_log "the stack already exists — bringing it up to date with deploy/update.sh"
    deploy/update.sh || ost_warn "the update did not go through (see above); the stack keeps running."
else
    image="$(ost_fetch_image)" || ost_die "could not pull or build the server image."
    "$ENGINE" tag "$image" "$OST_IMAGE_CURRENT"

    ost_log "starting the stack"
    ost_compose up -d >/dev/null
    ost_log "waiting for the server to report healthy on ${health_host}:${port}"
    if ! ost_wait_healthy 180; then
        ost_die "the server did not become healthy within 3 minutes — check: ${ENGINE} logs ${OST_SERVER}"
    fi

    ost_log "taking the first database backup"
    deploy/backup.sh initial >/dev/null || ost_warn "the first backup failed — check deploy/backup.sh by hand."
fi

ost_install_units "$auto_update"

cat <<EOF

==> OpenScreenTime is up and healthy on ${health_host}:${port}.

Next steps:

1. Point a reverse proxy at ${health_host}:${port} for https://${domain}.
   The app itself does not terminate TLS — your proxy must. It also must
   forward WebSocket upgrades (used by the agent channel).

   Minimal Caddy example (Caddy gets the certificate and handles WebSockets):

     ${domain} {
         reverse_proxy ${health_host}:${port}
     }

   Minimal nginx example:

     server {
         listen 443 ssl;
         server_name ${domain};

         location / {
             proxy_pass http://${health_host}:${port};
             proxy_http_version 1.1;
             proxy_set_header Upgrade \$http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host \$host;
             proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto \$scheme;
         }
     }

2. Open https://${domain} and create the first parent account. The page asks
   for a one-time setup code:

       $(ost_env OST_BOOTSTRAP_TOKEN)

   Registration locks the moment that first account exists.

3. In the console, click ADD DEVICE — it gives you a copy-paste installer
   one-liner to enroll each device.

From here on it runs by itself: it starts at boot, backs up nightly to
backups/ (copy that folder off this machine now and then), and updates daily
with an automatic rollback. For phone alerts when something needs you, see
docs/OPERATIONS.md ("Phone alerts").
EOF
